package uz.bot.variable.constants;

public interface UserStep {
    String STEP_START = "STEP_START";
    String STEP_ADD_DATA = "STEP_ADD_DATA";
    String STEP_GET_DATA = "STEP_GET_DATA";
    String STEP_DELETE_DATA = "STEP_GET_OTHER_DATA";
    String STEP_SET_NAME = "STEP_SET_NAME";
    String STEP_SET_SURNAME = "STEP_SET_SURNAME";
    String STEP_SET_BIRTHDATE = "STEP_SET_BIRTHDATE";
    String STEP_CHECKING_DATA = "STEP_CHECKING_DATA";


    String STEP_MODIFYING_USER = "STEP_MODIFYING_USER";
    String STEP_MODIFYING_DATA = "STEP_MODIFYING_DATA";
}
